steps:
  # 1. Build Gateway Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/citric-kit-489316-g6/ranjuartifactrepo/rjfrontendservice:latest', '-f', 'Dockerfile.gateway', '.']

  # 2. Build Product Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjproductservice:latest', '-f', 'Dockerfile.product', '.']

  # 3. Build Cart Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjcartservice:latest', '-f', 'Dockerfile.cart', '.']

  # 4. Build Order Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjorderservice:latest', '-f', 'Dockerfile.order', '.']

  # 5. Push all images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjfrontendservice:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjproductservice:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjcartservice:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/ranjuartifactrepo/rjorderservice:latest']

  # 6. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ranju-cp1-cluster-1 --zone asia-south1-c --project citric-kit-489316-g6
        kubectl apply -f deployment.yaml


options:
  logging: CLOUD_LOGGING_ONLY
